include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/app/modules/*/*.g.dart
    - lib/app/*.g.dart
    - test/**
linter:
  rules:
    public_member_api_docs: false
    avoid_web_libraries_in_flutter: false