name: Build and Release

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.18.0-11.1.pre'
    - run: flutter pub get
#     - run: flutter test
    - run: flutter build web --release
    - run: |
        cd build/web
        git init
        git config --global user.email rodrigo.pequeno6@gmail.com
        git config --global user.name rodrigopequeno
        git status
        git remote add origin https://${{secrets.commit_secret}}@github.com/rodrigopequeno/rodrigopequeno.github.io.git
        git add --all
        git commit -m "update"
        git push origin master -ff
        
